### ISSUE TITLE
Feature Request: Add example showing how to use DCGAN

### ISSUE THREAD

**Issue by atduskgreg** [kylemcdonald/ml-examples#1]
This paper on [Unsupervised Representation Learning with Deep Convolutional Generative Adversarial Networks](http://arxiv.org/abs/1511.06434) seems to have great potential for creative uses. Plus the authors have already put the code with a bunch of example applications on Github:

https://github.com/Newmu/dcgan_code

And it seems to have relatively similar dependencies to other examples in this repo.

I'm going to try to see if I can get dcgan up and running using ml-notebook and will report back what I find.

**Comment by kylemcdonald** [comment]
great! we were are also planning on adding it, so anything you find will be helpful.

here is the very rough outline for the workshop https://docs.google.com/document/d/1u6QvMysaM4jXcy7RYJUgWU3l3FF9bicPl_1S9WnaYkc/edit?usp=sharing

**Comment by kylemcdonald** [comment]
going to close this because it's become clear that it's counterproductive to run certain things without a GPU.
